"""empty message

Revision ID: 08717fcb019d
Revises: fc3ae6239402
Create Date: 2025-03-26 01:04:50.061495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08717fcb019d'
down_revision = 'fc3ae6239402'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_constraint('course_teacher_id_fkey', type_='foreignkey')
        batch_op.drop_column('teacher_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('course_teacher_id_fkey', 'user', ['teacher_id'], ['id'])

    # ### end Alembic commands ###
