"""empty message

Revision ID: 131b877757df
Revises: ebf2768d783e
Create Date: 2025-03-26 15:55:48.039477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '131b877757df'
down_revision = 'ebf2768d783e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lecture', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_url', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lecture', schema=None) as batch_op:
        batch_op.drop_column('video_url')

    # ### end Alembic commands ###
