"""empty message

Revision ID: b62fd107e3ba
Revises: 131b877757df
Create Date: 2025-03-26 17:08:11.638909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b62fd107e3ba'
down_revision = '131b877757df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lecture_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'lecture', ['lecture_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('lecture_id')

    # ### end Alembic commands ###
