"""empty message

Revision ID: fc3ae6239402
Revises: 53eca223a905
Create Date: 2025-03-24 19:21:17.766233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc3ae6239402'
down_revision = '53eca223a905'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.alter_column('target_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.alter_column('target_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
