name: Flask CI Pipeline

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main


jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v2

      # 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Setup, Install, and Test
        run: |
          cd Doner_backend
          
          # 创建虚拟环境并激活
          python -m venv donerenv
          source donerenv/bin/activate
          
          # 安装依赖（不安装依赖项的依赖）
          pip install --no-deps -r requirements.txt
          
          # 写入 .env 文件（整个内容来自 GitHub Secret）
          echo "${{ secrets.secrets_env }}" > .env
          
          # 运行 Pytest
          pytest
        shell: bash  # 确保使用 bash，这样 source 可以正常工作

