name: Flask CI Pipeline

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main

jobs:
  pytest:
    runs-on: [self-hosted]   # <‑‑ 关键

    steps:
      - uses: actions/checkout@v4

      # ⚠️ 只在第一次或依赖变化时安装依赖
      - name: Ensure venv & deps
        run: |
          cd Doner_backend
          if [ ! -d donerenv ]; then
            echo "Creating virtualenv…"
            python3.12 -m venv donerenv
          fi
          source donerenv/bin/activate
          pip install --upgrade pip
          pip install --upgrade -r requirements.txt
      - name: Run tests
        env:
          SECRET_ENV: ${{ secrets.secrets_env }}
        run: |
          cd Doner_backend
          source donerenv/bin/activate
          echo "$SECRET_ENV" > .env
          pytest