name: Flask CI Pipeline

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
    paths:
      - 'Doner_backend/**'


jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v2

      # 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      # 安装依赖
      - name: Install dependencies
        run: |
          python Doner_backend/set_env.py

      # 运行 flask run 检查是否启动成功
      - name: Run Pytest
        run: |
          cd Doner_backend
          source donerenv/bin/activate
          pytest

      - name: Fail if tests fail
        if: failure()  # 如果测试失败，则整个工作流失败
        run: exit 1
